plugin: azure_rm
vars_files:
  - vars.yaml
include_vm_resource_groups:
  - rg-uit-{{env}}-{{stage}}
auth_source: auto
conditional_groups:
  RedHat: "'RHEL' in image.offer"
  Ubuntu: "'UbuntuServer' in image.offer"