plugin: azure_rm
include_vm_resource_groups:
  - '\*'
auth_source: auto
conditional_groups:
  RedHat: "'RHEL' in image.offer"
  Ubuntu: "'UbuntuServer' in image.offer"
keyed_groups:
- prefix: tag
  key: tags