# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.require_version ">= 1.7.0"

N = 1
#IMAGE_NAME = "bento/ubuntu-18.04"
IMAGE_NAME = "generic/rhel8"

Vagrant.configure("2") do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false
  config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
            node.vm.hostname = "node-#{i}"
        end
    end  
    
#     config.vm.provision "ansible" do |ansible|
#     ansible.verbose = "v"
#     ansible.playbook = "playbook.yaml"
#  end
end