---
ansible_pass: !unsafe 'Just4PrototypingAsPlaintext'

sshkeys:
  ansible:
    - name: JG ssh key cardno:000500009EE4
      sshkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCnyhjsy++IxWO+M3dcQu2GCylXqHKKGy6pqeLxr9rT7JpE+DHoi3ZI+Jrw50X0heKOvjby9w/GUE/3kaW83LbJXs9ebnTB675ycrHIvcUvY6dhwRtseKOauZLAqcosrZhI5BBKUg8ord03pTeHqc6fnmm32Ab+MfhZEKnoz+n/X2jhY3e2AG4Hwx7k5y8IZK4TPzYTtIReEW9qGxc3KqBpYBgq/0LnWGJXeF5MO/9DCsjpCLuwbWUgqkVeQ97j1g6WAtu0p0oNBh9fRzdrfmJdClPPRsA81V7GW4BTflVs9A900xF2tZ+Is9DYH2XzZC4z6mx/TpAxc28N1l8ixoRjwAfJ3GsA+NKqn96//MYHPWIHp5SuqJl1ro2ZwOglSqJEDQK1ruzPkGNh5xtZkucl7zDfcc2r2J5S8jk9wBnhjupSENvsggwVM67QuQ2XqHT2hPvGgSwMGmBgdXExp3h96uwDi7+DxcfDQKP2XaV745vA7foGpJ3nNfQODetCNJ7Sxk6BWGBGi5CmY72lKMCildgs242oFxOCHpRhbyCSyNSgM6rgkR82YRHqZ+PGq9Gm4MkR+LHClCPyt9trE+KXnEpmD9amn17Ai6PSYR/x0pnFjbFAwxOqv6jeRokO7lA1cBHAnWhSlhRVZacAHRXT/k0d8j9yei/rsMKsS9EGGQ== JG cardno:000500009EE4"

...